version: '3.7'

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  node:
    image: node:12.16.1
    container_name: node
    restart: always
    volumes:
      - ./transcendence:/usr/src/app
      # - type: bind
      #   source: ./transcendence
      #   target: /usr/src/app
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run start:dev"
    networks:
      my-network:
        ipv4_address: 10.0.0.10

  postgres:
    image: postgres:latest
    container_name: pg_database
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - ./env/.postgres.env
    networks:
      my-network:
        ipv4_address: 10.0.0.11
    expose:
      - 5432

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - ./env/.pgadmin.env
    ports:
      - 5050:80
    networks:
      my-network:
        ipv4_address: 10.0.0.12
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin