version: '3.7'

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  node:
    image: node:12.16.1
    container_name: node
    restart: always
    volumes:
      - /Users/babdelka/Desktop/git/ft_transcendence/transcendence:/usr/src/app
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run start"
    networks:
      my-network:
        ipv4_address: 10.0.0.10

  postgres:
    image: postgres:latest
    container_name: pg_database
    restart: always
    volumes:
      - /Users/babdelka/Desktop/git/ft_transcendence/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: trs_db 
    networks:
      my-network:
        ipv4_address: 10.0.0.11
    ports:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    networks:
      my-network:
        ipv4_address: 10.0.0.12
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin